name: Keep Render Alive

on:
  schedule:
    # Every 10 minutes (UTC)
    - cron: "*/10 * * * *"
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render health endpoint
        run: curl -sS https://wifmartservices.onrender.com/api/health || true


